# Generated by Django 4.1.4 on 2022-12-10 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.CharField(max_length=250)),
                ('titulo', models.CharField(max_length=150)),
                ('descripcion', models.CharField(max_length=200)),
                ('tags', models.CharField(max_length=80)),
                ('url_github', models.CharField(max_length=250)),
            ],
        ),
    ]
